---
title: "Data Visualizations"
author: "Chris Leggett"
date: "2023-11-08"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Install packages
```{r}
library(ggplot2)
library(dplyr)
library(tidyverse)
library(rprojroot)
library(naniar)
library(viridis)
library(gridExtra)
```

## get cleaned data

```{r}
project_path <- find_rstudio_root_file()
rawdata_path <- paste0(project_path, "/raw_data/")
data_path <- paste0(project_path, "/data/")
code_path <- paste0(project_path, "/code/")
cleandata <- readRDS(file = paste0(data_path,"cleandata.rds"))
cleandata2 <- readRDS(file = paste0(data_path,"cleandata2.rds"))
```

## source functions library
```{r}
source(file = paste0(code_path, "functions.R"))
```



## Bar chart showing maximum cases by country
```{r}
# cases
cleandata_grouped <- cleandata %>%
     group_by(Country) %>%
     summarize(max_cases = max(Cases)) 
p1 <-ggplot(cleandata_grouped, aes(x = Country, y = max_cases)) +
     geom_bar(position = "dodge", stat = "identity", fill = "steelblue") +
     labs(y = "Total Cases", x = "") +
     coord_flip() +
     theme_classic()

# logged cases
cleandata_grouped$log_cases = log(cleandata_grouped$max_cases)
p2 <-ggplot(cleandata_grouped, aes(x = Country, y = log_cases)) +
     geom_bar(position = "dodge", stat = "identity", fill = "steelblue") +
     labs(y = "Log of Total Cases", x = "") +
     coord_flip() +
     theme_classic()

grid.arrange(p1, p2, ncol = 2)

```



## Line graphs of cases and deaths
```{r}


#################################################################
# cumulative cases

# all countries at once
ggplot(cleandata2, aes(x = Date, y = Cases, color = Country)) +
    # geom_line() +
     scale_color_viridis(discrete = TRUE) +
     geom_point() +
     theme_classic()


#  one country at a time in grid plot
p1 <- plot_one(country = "China", yvar = "Cases")
p2 <- plot_one(country = "Hong Kong", yvar = "Cases")
p3 <- plot_one(country = "Taiwan", yvar = "Cases")
p4 <- plot_one(country = "Singapore", yvar = "Cases")
p5 <- plot_one(country = "Canada", yvar = "Cases")
p6 <- plot_one(country = "USA", yvar = "Cases")
p7 <- plot_one(country = "Philippines", yvar = "Cases")
p8 <- plot_one(country = "Germany", yvar = "Cases")
p9 <- plot_one(country = "Vietnam", yvar = "Cases")
grid.arrange(p1, p2, p3, p4, p5, p6, p7, p8, p9, ncol = 3, bottom = "DAILY CUMULATIVE CASES BY COUNTRY")



#################################################################
# Deaths

# all countries at once
ggplot(cleandata2, aes(x = Date, y = Deaths, color = Country)) +
    # geom_line() +
     scale_color_viridis(discrete = TRUE) +
     geom_point() +
     theme_classic()


#  one country at a time in grid plot
p1 <- plot_one(country = "China", yvar = "Deaths")
p2 <- plot_one(country = "Hong Kong", yvar = "Deaths")
p3 <- plot_one(country = "Taiwan", yvar = "Deaths")
p4 <- plot_one(country = "Singapore", yvar = "Deaths")
p5 <- plot_one(country = "Canada", yvar = "Deaths")
p6 <- plot_one(country = "USA", yvar = "Deaths")
p7 <- plot_one(country = "Philippines", yvar = "Deaths")
p8 <- plot_one(country = "Germany", yvar = "Deaths")
p9 <- plot_one(country = "Vietnam", yvar = "Deaths")
grid.arrange(p1, p2, p3, p4, p5, p6, p7, p8, p9, ncol = 3, bottom = "DAILY DEATHS BY COUNTRY")





#################################################################
# Incident Cases

# all countries at once
ggplot(cleandata2, aes(x = Date, y = New_Cases, color = Country)) +
    # geom_line() +
     scale_color_viridis(discrete = TRUE) +
     geom_point() +
     theme_classic()


#  one country at a time in grid plot
p1 <- plot_one(country = "China", yvar = "New_Cases")
p2 <- plot_one(country = "Hong Kong", yvar = "New_Cases")
p3 <- plot_one(country = "Taiwan", yvar = "New_Cases")
p4 <- plot_one(country = "Singapore", yvar = "New_Cases")
p5 <- plot_one(country = "Canada", yvar = "New_Cases")
p6 <- plot_one(country = "USA", yvar = "New_Cases")
p7 <- plot_one(country = "Philippines", yvar = "New_Cases")
p8 <- plot_one(country = "Germany", yvar = "New_Cases")
p9 <- plot_one(country = "Vietnam", yvar = "New_Cases")
grid.arrange(p1, p2, p3, p4, p5, p6, p7, p8, p9, ncol = 3, bottom = "DAILY INCIDENT CASES BY COUNTRY")


#################################################################
# Case fatality rate

# all countries at once
cleandata2$case_fatality = cleandata2$Deaths/cleandata2$Cases
ggplot(cleandata2, aes(x = Date, y = case_fatality, color = Country)) +
    # geom_line() +
     scale_color_viridis(discrete = TRUE) +
     geom_point() +
     theme_classic()


#  one country at a time in grid plot
p1 <- plot_one(country = "China", yvar = "case_fatality")
p2 <- plot_one(country = "Hong Kong", yvar = "case_fatality")
p3 <- plot_one(country = "Taiwan", yvar = "case_fatality")
p4 <- plot_one(country = "Singapore", yvar = "case_fatality")
p5 <- plot_one(country = "Canada", yvar = "case_fatality")
p6 <- plot_one(country = "USA", yvar = "case_fatality")
p7 <- plot_one(country = "Philippines", yvar = "case_fatality")
p8 <- plot_one(country = "Germany", yvar = "case_fatality")
p9 <- plot_one(country = "Vietnam", yvar = "case_fatality")
grid.arrange(p1, p2, p3, p4, p5, p6, p7, p8, p9, ncol = 3, bottom = "DAILY CASE FATALITY BY COUNTRY")
```






