---
title: "qbs181_examine_missing_data"
author: "Chris Leggett"
date: "2023-11-04"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Libraries
```{r}
library(ggplot2)
library(dplyr)
library(tidyverse)
library(rprojroot)
library(naniar)
```


## Get clean data

```{r}
project_path <- find_rstudio_root_file()
data_path <- paste0(project_path, "/data/")
cleandata <- readRDS(file = paste0(data_path,"cleandata.rds"))
cleandata2 <- readRDS(file = paste0(data_path,"cleandata2.rds"))
```


## Evaluate missingness

```{r}

# dates with missing data are invisible because they are not in the dataset
# so we create a df that has ALL dates within the range of the raw data
dates <- seq.Date(from = as.Date(min(cleandata$Date)), 
                  to = as.Date(max(cleandata$Date)),1)
dates_df <- as.data.frame(dates, col.names = c("Date"))
names(dates_df) <- "Date"
dates_df$Country <- "Dummy"

# append this dates df to our raw data
df <- bind_rows(cleandata, dates_df)

# reshape to wide, focusing on "Cases" column
cases <- df[c("Date","Country","Cases")]
cases_wide <- spread(cases, key = Country, value = Cases) %>%
     mutate(Week = as.numeric(format(Date, "%W")) - 10,
            DOW = as.factor(weekdays(Date)))
cases_wide$DOW <- factor(cases_wide$DOW, 
                            levels = c("Sunday",
                                       "Monday",
                                       "Tuesday",
                                       "Wednesday",
                                       "Thursday",
                                       "Friday",
                                       "Saturday"))

# plot overall missingness pattern
cases_wide_for_plot <- cases_wide %>%
     select(!c(Date,Dummy,Week,DOW))
vis_miss(cases_wide_for_plot) + 
     labs(y = "Days since 3/17/2003") 

# colorful version of overall missingness pattern
cases_wide_for_daily_plot <- cases_wide %>%
     select(!c(Dummy,Week,DOW))
gg_miss_fct(cases_wide_for_daily_plot, Date) + 
     labs(x = " ", y = "") 

# plot percent missing by week and day of week
cases_wide_for_weekly_plot <- cases_wide %>%
     select(!c(Date,Dummy,DOW)) %>%
     filter(Week != 17)
gg_miss_fct(cases_wide_for_weekly_plot, Week) +
          labs(x = "Weeks since 3/17/2003", y = "") 
cases_wide_for_DOW_plot <- cases_wide %>%
     select(!c(Date,Dummy,Week)) 
gg_miss_fct(cases_wide_for_DOW_plot, DOW) +
          labs(x = "", y = "") 
cases_wide_for_weekly_plot_subset <- cases_wide %>%
     select(Week, China, USA, Philippines, Vietnam, `Hong Kong`, Taiwan, Singapore, Canada, Germany) %>%
     filter(Week != 17)
gg_miss_fct(cases_wide_for_weekly_plot_subset, Week) +
          labs(x = "Weeks since 3/17/2003", y = "") 



# plot missingness by day of week
missing_byDate <- cases_wide %>%
     mutate(num_missing = rowSums(is.na(cases_wide)),
            num_obs = rowSums(is.na(cases_wide) + !is.na(cases_wide))) %>%
     select(Date, 
            num_missing, 
            num_obs, 
            DOW)
missing_byDOW <- missing_byDate %>%
     group_by(DOW) %>%
     summarize(missing = sum(num_missing),
               total = sum(num_obs)) %>%
     mutate(perc_missing = 100*missing/total,
            perc_fmt = format(perc_missing,digits = 3))
ggplot(missing_byDOW,aes(x=DOW,y=perc_missing))+
  geom_bar(stat="identity", fill="#440154FF", width = .6) +
  geom_text(aes(label=perc_fmt), vjust=1.6, color="white", size=3.5)+
  labs(y="Percent Missing", x = " ") +
  theme_classic()
```


## heat map for selected countries
```{r}
heatdata <- cleandata %>%
     select(Date, Country, New_Cases) %>%
     filter(Country %in% c('China', 'USA', 'Philippines', 'Vietnam', 'Hong Kong', 'Taiwan', 'Singapore', 'Canada', 'Germany'))

ggplot(heatdata, aes(Country, Date, fill = New_Cases)) +
     geom_tile() +
     coord_flip() +
     labs(y=" ", x = " ") +
     theme_classic()

```


